### ISSUE TITLE
cachedb_redis: AUTH support

### ISSUE THREAD

**Issue by v1cdang** [OpenSIPS/opensips-cli#58]
Any chance you can put auth for the redis module?

**Comment by liviuchircu** [comment]
hey, @v1cdang -- do I smell an [OpenSIPS feature request](https://github.com/OpenSIPS/opensips/issues) for the `cachedb_redis` module? :) If not, then please elaborate, as I have no clue on how Redis ties in with OpenSIPS CLI.

**Comment by v1cdang** [comment]
Yes this should be a feature request if it's not yet capable of doing redis
auth,

**Comment by liviuchircu** [comment]
You didn't answer my question - so this is a `cachedb_redis` feature, so we allow users to plug in a username/password into it before being able to use their Redis instance?

**Comment by v1cdang** [comment]
yes, you need to allow for username/password for redis instance as well.

**Comment by liviuchircu** [comment]
Within the `cachedb_redis` module, if we take a look at the `redis_connect()` function, you can see that [it already includes](https://github.com/OpenSIPS/opensips/blob/master/modules/cachedb_redis/cachedb_redis_dbase.c#L138) Redis "AUTH <password>" support.  However, I've noticed that Redis 6 introduced a new flavour of the command: "AUTH <username> <password>", which seems to relate to the new ACL concepts.

Can you relate to the above?  Is the current password-based auth support not enough for you, since you are using Redis ACLs?  Thanks!

**Comment by v1cdang** [comment]
Thanks for pointing that out. Where do I set that on opensips.cfg?

**Comment by liviuchircu** [comment]
Just include the password in the `cachedb_url` module parameter.  I _think_ that the username will be ignored, please test and confirm.  For example:

```
modparam("cachedb_redis", "cachedb_url", "redis:cluster1://user:pass@localhost:6379")
```
